### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by antonio-fr**
Trezor bower
Network type name variable

### CODE REVIEW

**Comment by troggy** [comment]
what's with all those commits in this PR?

**Comment by antonio-fr** [comment]
I merged on my local side before submitting it. Idk why your previous commits are shown here, I imagine they would disappear if you accept this PR. There are only 2 'real' commits from me. all commits except mine, are already present in this repo.
Tell me if you want a very clean PR.

**Comment by troggy** [comment]
Yes, would be good to have a clean PR please

**Comment by troggy** [comment]
On a second thought as your fixes are small I think I will just merge them manually

**Comment by troggy** [comment]
Merged:
https://github.com/Colored-Coins/colored-coins-copay-wallet/commit/dde36ed6c086c70838a1991a8655035e7b2a3205
https://github.com/Colored-Coins/colored-coins-copay-wallet/commit/32e65da200b8420b15c2245e5ab133fc45138140

Thanks for the help!

**Pull request closed without merging**
